#!/usr/bin/env node
/**
 * Regenerates `docs/cli-ui-coverage.md` — the one place this documentation
 * system states which CLI commands have a UI route that reads the same data,
 * which do not, and what only the UI answers.
 *
 *   npm run gen:docs
 *
 * `TASK-disclose-where-cli-and-ui-coverage-differ-derived-from-the`
 * (`plan:docsys seq:7`). It is wired into the `gen:docs` family rather than
 * given its own invocation, per the task's own instruction: a fourth generator
 * with a fourth command is a fourth thing to remember to run, and the whole
 * point of this file is that nobody has to remember anything.
 *
 * **Everything below the banner is derived from the running program.** The
 * command list is `COMMANDS` after `src/cli/index.ts` has registered every
 * command (including the seven that were once dispatched by a hardcoded
 * `switch`); the route list is `registeredRoutes()` after
 * `registerReadRoutes()` has filled the table the server itself dispatches
 * from. Nothing is typed here but the prose that explains what the numbers
 * mean, and `test/docs/doc-system.test.ts` regenerates the file and fails on
 * any difference — a hand-edited row is the exact defect this generator
 * exists to prevent.
 *
 * Importing this module has no side effect (the `isMainEntry` gate every
 * generator and hook binary in this repository uses), so the test can call
 * `renderCoverageDocument` directly and compare.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { isMainEntry } from '../src/core/paths.ts';
import {
  deriveCliUiCoverage, type CliCommandFact, type CliUiCoverage, type UiRouteFact,
} from '../src/core/cli-ui-coverage.ts';

/** Where the generated document lives, repo-relative. */
export const COVERAGE_DOC_PATH = 'docs/cli-ui-coverage.md';

/** A table cell: the pipes in `add`'s own usage summary would otherwise close
 * the column three characters into the sentence. */
function cell(text: string): string {
  return text.replaceAll('|', '\\|');
}

/**
 * The whole document, as a string. Pure — it reads no file and touches no
 * clock, so the test can call it with the program's own inputs and diff the
 * result against what is committed.
 */
export function renderCoverageDocument(
  commands: CliCommandFact[],
  routes: UiRouteFact[],
): string {
  const coverage: CliUiCoverage = deriveCliUiCoverage(commands, routes);
  const lines: string[] = [];

  lines.push('# CLI and UI coverage');
  lines.push('');
  lines.push('<!-- GENERATED by scripts/gen-cli-ui-coverage.ts (`npm run gen:docs`).');
  lines.push('     Do not edit this file: `test/docs/doc-system.test.ts` regenerates it and');
  lines.push('     fails on any difference. -->');
  lines.push('');
  lines.push(
    `my_context has ${coverage.rows.length} CLI commands and ${routes.length} registered UI ` +
    `read routes. ${coverage.covered} of the commands have a route that reads the same data; ` +
    `${coverage.cliOnly} have none at all, and ${coverage.uiOnly.length} routes answer a ` +
    'question no command asks.',
  );
  lines.push('');
  lines.push('**The UI is read-only, so this table is about READING.** Every route below reads;');
  lines.push('none of them changes anything, and `test/ui/no-writes.test.ts` holds the server\'s');
  lines.push('import graph to that. Where a command CHANGES the corpus — every `add`, `edit`,');
  lines.push('`review`, `import` and `refresh` among them — that half of the command is CLI-only');
  lines.push('whatever the verdict column says beside it, and the browser composes the command for');
  lines.push('you to run rather than running it.');
  lines.push('');
  lines.push('**How "reads the same data" was decided.** A route covers a command when the');
  lines.push('route\'s own path names it — `/api/decay` covers `decay`, `/api/sessions` covers');
  lines.push('`session`. Five pairs whose names disagree are declared in');
  lines.push('`src/core/cli-ui-coverage.ts` with a sentence each, and the same test holds those');
  lines.push('declarations to a command and a route that both still exist.');
  lines.push('');
  lines.push('## Every CLI command');
  lines.push('');
  lines.push('| command | what it does | UI route | what the UI offers |');
  lines.push('| --- | --- | --- | --- |');
  for (const row of coverage.rows) {
    const routeCell = row.routes.length === 0
      ? '—'
      : row.routes.map((r) => `\`${r}\``).join('<br>');
    lines.push(
      `| \`mycontext ${row.command}\` | ${cell(row.summary)} | ${routeCell} | ${cell(row.note)} |`,
    );
  }
  lines.push('');
  lines.push('## What only the UI answers');
  lines.push('');
  lines.push('These routes carry no command\'s name. Some are the browser\'s own plumbing, some');
  lines.push('are screens the terminal has no equivalent of at all — a reader comparing the two');
  lines.push('surfaces needs the list either way.');
  lines.push('');
  lines.push('| route |');
  lines.push('| --- |');
  for (const route of coverage.uiOnly) {
    lines.push(`| \`${route.method} ${route.path}\` |`);
  }
  lines.push('');
  return lines.join('\n');
}

/** The command surface, as the program itself holds it. */
export async function liveCommands(): Promise<CliCommandFact[]> {
  const { COMMANDS } = await import('../src/cli/commands/registry.ts');
  // Registers everything, including the seven builtins `index.ts` itself
  // registers — importing the registry alone would silently miss them.
  await import('../src/cli/index.ts');
  return [...COMMANDS.values()].map((c) => ({ name: c.name, summary: c.summary }));
}

/** The read-route table, as the server itself holds it. */
export async function liveRoutes(): Promise<UiRouteFact[]> {
  const { registerReadRoutes } = await import('../src/ui/server.ts');
  const { registeredRoutes } = await import('../src/ui/routes.ts');
  registerReadRoutes();
  return registeredRoutes();
}

if (isMainEntry(import.meta.filename, process.argv[1])) {
  const file = path.join(import.meta.dirname, '..', ...COVERAGE_DOC_PATH.split('/'));
  const rendered = renderCoverageDocument(await liveCommands(), await liveRoutes());
  let before = '';
  try {
    before = readFileSync(file, 'utf8').replaceAll('\r\n', '\n');
  } catch {
    before = '';
  }
  writeFileSync(file, rendered, 'utf8');
  console.log(
    before === rendered
      ? `${COVERAGE_DOC_PATH} is unchanged`
      : `wrote ${COVERAGE_DOC_PATH}`,
  );
}
