// harness/cases/cli-capture.mjs
const ADD = ['add', 'constraint', 'Uploads capped at 10 MB'];

export const cases = [
  // --- init ---
  { id: 'init-on-pristine-dir', kind: 'cli', pristine: true, argv: ['init'],
    note: 'init on a genuinely empty directory: expected exit 0, creates .my_context/{items,config.json,.gitignore}' },
  { id: 'init-on-initialised-dir', kind: 'cli', argv: ['init'],
    note: 'init re-run against an already-initialised workspace: records the refusal' },
  { id: 'init-global-refused', kind: 'cli', argv: ['init', '--global'],
    note: 'README 4494: refused, names the global root' },
  { id: 'init-unknown-arg', kind: 'cli', argv: ['init', '--nope'],
    note: 'README 2841 lists init as NOT checking unknown flags — contradicts 4494' },

  // --- add: accepted flags ---
  { id: 'add-normative-without-yes', kind: 'cli', argv: [...ADD],
    note: 'normative category should require --yes' },
  { id: 'add-normative-with-yes', kind: 'cli', argv: [...ADD, '--yes'] },
  { id: 'add-rationale-without-yes', kind: 'cli', argv: ['add', 'decision', 'We chose Stripe'],
    note: 'rationale needs no --yes' },
  { id: 'add-body', kind: 'cli', argv: [...ADD, '--body', 'Gateway rejects larger bodies.', '--yes'] },
  { id: 'add-scope-comma', kind: 'cli', argv: [...ADD, '--scope', 'src/api/**,src/db/**', '--yes'] },
  { id: 'add-scope-repeated', kind: 'cli',
    argv: [...ADD, '--scope', 'src/api/**', '--scope', 'src/db/**', '--yes'],
    note: 'README 1926: comma and repeat forms must be equivalent' },
  { id: 'add-tags', kind: 'cli', argv: [...ADD, '--tags', 'uploads,api', '--yes'] },
  { id: 'add-severity-hard', kind: 'cli', argv: [...ADD, '--severity', 'hard', '--yes'] },
  { id: 'add-severity-soft', kind: 'cli', argv: [...ADD, '--severity', 'soft', '--yes'] },
  { id: 'add-note-repeated', kind: 'cli',
    argv: [...ADD, '--note', 'first', '--note', 'second', '--yes'],
    note: 'repeatable: one observation per occurrence' },
  { id: 'add-equals-form', kind: 'cli', argv: [...ADD, '--severity=hard', '--yes'] },

  // --- add: readback cases (verify claims in notes) ---
  { id: 'add-scope-comma-readback', kind: 'cli',
    setup: [[...ADD, '--scope', 'src/api/**,src/db/**', '--yes']],
    argv: ['show', 'CONST-uploads-capped-at-10-mb'],
    note: 'reads back the stored scope for the comma form; compare with the repeated form' },
  { id: 'add-scope-repeated-readback', kind: 'cli',
    setup: [[...ADD, '--scope', 'src/api/**', '--scope', 'src/db/**', '--yes']],
    argv: ['show', 'CONST-uploads-capped-at-10-mb'],
    note: 'reads back the stored scope for the repeated form; README 1926 says these must be equivalent' },
  { id: 'add-note-repeated-readback', kind: 'cli',
    setup: [[...ADD, '--note', 'first', '--note', 'second', '--yes']],
    argv: ['show', 'CONST-uploads-capped-at-10-mb'],
    note: 'reads back observations; one per --note occurrence is the documented behaviour' },

  // --- add: refusals ---
  { id: 'add-body-and-file-conflict', kind: 'cli',
    argv: [...ADD, '--body', 'x', '--file', 'README.md', '--yes'],
    note: 'README 1928: --body and --file together refused' },
  { id: 'add-repeated-single-value', kind: 'cli',
    argv: [...ADD, '--body', 'x', '--body', 'y', '--yes'],
    note: 'README 1927: single-valued flag twice is refused' },
  { id: 'add-unknown-flag', kind: 'cli', argv: [...ADD, '--nope', '--yes'] },
  { id: 'add-value-flag-with-nothing-after', kind: 'cli', argv: [...ADD, '--body'] },
  { id: 'add-unknown-category', kind: 'cli', argv: ['add', 'nosuchtype', 'X', '--yes'] },
  { id: 'add-yes-maybe', kind: 'cli', argv: [...ADD, '--yes=maybe'],
    note: 'README 2830: --yes=maybe refused' },
  { id: 'add-yes-false', kind: 'cli', argv: [...ADD, '--yes=false'],
    note: 'declines rather than confirms' },
  { id: 'add-severity-hard-on-rationale', kind: 'cli',
    argv: ['add', 'decision', 'X', '--severity', 'hard'],
    note: 'README 3974: refused on rationale' },

  // --- list / show ---
  { id: 'list-bare', kind: 'cli', setup: [[...ADD, '--yes']], argv: ['list'] },
  { id: 'list-category', kind: 'cli', setup: [[...ADD, '--yes']], argv: ['list', 'constraint'] },
  { id: 'list-full', kind: 'cli', setup: [[...ADD, '--yes']], argv: ['list', '--full'] },
  { id: 'list-short', kind: 'cli', setup: [[...ADD, '--yes']], argv: ['list', '--short'] },
  { id: 'list-summary', kind: 'cli', setup: [[...ADD, '--yes']], argv: ['list', '--summary'] },
  { id: 'list-json', kind: 'cli', setup: [[...ADD, '--yes']], argv: ['list', '--json'] },
  { id: 'list-two-detail-levels', kind: 'cli', argv: ['list', '--full', '--short'],
    note: 'two levels at once is an error' },
  { id: 'list-unknown-category', kind: 'cli', argv: ['list', 'nosuchtype'] },
  { id: 'show-existing', kind: 'cli', setup: [[...ADD, '--yes']],
    argv: ['show', 'CONST-uploads-capped-at-10-mb'] },
  { id: 'show-missing', kind: 'cli', argv: ['show', 'CONST-does-not-exist'] },
  { id: 'show-unknown-flag', kind: 'cli', setup: [[...ADD, '--yes']],
    argv: ['show', 'CONST-uploads-capped-at-10-mb', '--nope'],
    note: 'README 2841: show does NOT check unknown flags' },

  // --- status / doctor ---
  { id: 'status-bare', kind: 'cli', argv: ['status'] },
  { id: 'status-json', kind: 'cli', argv: ['status', '--json'] },
  { id: 'status-summary', kind: 'cli', argv: ['status', '--summary'] },
  { id: 'status-full', kind: 'cli', argv: ['status', '--full'] },
  { id: 'status-unknown-flag', kind: 'cli', argv: ['status', '--nope'] },
  { id: 'doctor-bare', kind: 'cli', argv: ['doctor'] },
  { id: 'doctor-quiet', kind: 'cli', argv: ['doctor', '--quiet'] },
  { id: 'doctor-quiet-and-full', kind: 'cli', argv: ['doctor', '--quiet', '--full'],
    note: 'README 2785: --quiet wins and nothing says so' },
  { id: 'doctor-json', kind: 'cli', argv: ['doctor', '--json'] },

  // --- help / examples / rebuild ---
  { id: 'help-bare', kind: 'cli', argv: ['help'] },
  { id: 'help-categories', kind: 'cli', argv: ['help', 'categories'] },
  { id: 'help-scope', kind: 'cli', argv: ['help', 'scope'] },
  { id: 'help-capture', kind: 'cli', argv: ['help', 'capture'] },
  { id: 'help-workflow', kind: 'cli', argv: ['help', 'workflow'] },
  { id: 'help-query-refused', kind: 'cli', argv: ['help', 'query'],
    note: 'README 4483: refused by name' },
  { id: 'help-config-refused', kind: 'cli', argv: ['help', 'config'] },
  { id: 'examples-rule', kind: 'cli', argv: ['examples', 'rule'] },
  { id: 'examples-short', kind: 'cli', argv: ['examples', 'rule', '--short'] },
  { id: 'examples-unknown', kind: 'cli', argv: ['examples', 'nosuchtype'] },
  { id: 'rebuild-bare', kind: 'cli', setup: [[...ADD, '--yes']], argv: ['rebuild'] },
  { id: 'rebuild-with-args-dropped', kind: 'cli', argv: ['rebuild', '--nope'],
    note: 'args deliberately dropped at index.ts:811' },

  // --- top level ---
  { id: 'bare-invocation', kind: 'cli', argv: [], note: 'exits 1' },
  { id: 'help-flag', kind: 'cli', argv: ['--help'], note: 'exits 0' },
  { id: 'unknown-command', kind: 'cli', argv: ['nosuchcommand'] },
];
